name: Build and Test and Merge
on:
  push:
    branches-ignore:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: echos github.ref
      run: |
        echo '$GITHUB_REF     =' $GITHUB_REF
        echo 'github.ref      =' ${{ github.ref }}
        echo 'github.ref_name =' ${{ github.ref_name }}
        echo 'github.head_ref =' ${{ github.head_ref }}
        echo 'github.base_ref =' ${{ github.base_ref }}

    - name: Checkout for build and test
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build
      env:
        AWS_BASE_URL: ${{ secrets.AWS_BASE_URL }}
        GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}

    - name: Test with Gradle
      run: ./gradlew test
      env:
        AWS_BASE_URL: ${{ secrets.AWS_BASE_URL }}
        GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}

    - name: Archive debug test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: debug-test-results
        path: app/build/reports/tests/testDebugUnitTest

    - name: Archive release test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: release-test-results
        path: app/build/reports/tests/testReleaseUnitTest

  merge:
    needs: build_and_test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout for merge
      uses: actions/checkout@v4
      with:
        ref: main

    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email ""

    - name: Merge branch
      run: |
        git fetch origin
        git branch -a
        echo "marge : ${{ github.ref_name }} -> main"
        git merge --no-ff --no-edit origin/${{ github.ref_name }}
        git push origin main

    - name: Delete branch
      run: echo ${{ github.ref_name }} | xargs git push origin --delete